### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by skarmiglione** [Barrett17/V-OS#3] opened 2018-09-20 22:25 UTC
autoconf && ./configure && make
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for printf in -lstdc... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for pthread_kill in -lpthread... yes
checking for dlopen in -ldl... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking png.h usability... yes
checking png.h presence... yes
checking for png.h... yes
checking for png_read_info in -lpng... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for jpeg_destroy_decompress in -ljpeg... yes
checking jpeglib.h usability... yes
checking jpeglib.h presence... yes
checking for jpeglib.h... yes
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking for freetype-config... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking whether gcc needs -traditional... no
checking whether to enable DirectFB graphics rendering... no
checking whether to enable SDL graphics rendering... no
checking whether to enable XWindows graphics rendering... yes
checking for XOpenDisplay in -lX11... yes
checking X11/Xlib.h usability... yes
checking X11/Xlib.h presence... yes
checking for X11/Xlib.h... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating cosmoe.specs
config.status: creating headers/Makefile
config.status: creating src/kits/Makefile
config.status: creating src/system/Makefile
config.status: creating src/libs/icon/Makefile
config.status: creating src/libs/linprog/Makefile
config.status: creating src/libs/agg/Makefile
config.status: creating src/servers/app/Makefile
config.status: creating src/servers/registrar/Makefile
config.status: creating src/apps/Makefile
config.status: creating src/apps/testharness/Makefile
config.status: creating src/apps/osutils/Makefile
config.status: creating config.h
config.status: config.h is unchanged
make[1]: se entra en el directorio '/home/cmkat/src/V-OS-master/headers'
make[1]: No se hace nada para 'all'.
make[1]: se sale del directorio '/home/cmkat/src/V-OS-master/headers'
make[1]: se entra en el directorio '/home/cmkat/src/V-OS-master/src/libs/icon'
gcc -include build/BeOSBuildCompatibility.h -Wall -Wpointer-arith -Wcast-align -Wsign-compare -Wno-multichar -c -g -O2 -pipe `cat ../../../cosmoe.specs` -fPIC -Woverloaded-virtual -Wno-ctor-dtor-privacy -Wnon-virtual-dtor -fexceptions -fpermissive -M Icon.cpp | sed 's%^\(.*\):%../../../objs\/\1:%' > ../../../objs/*.d
ar rcs ../../../objs/libicon.a ../../../objs/FlatIconFormat.o ../../../objs/FlatIconImporter.o ../../../objs/LittleEndianBuffer.o ../../../objs/PathCommandQueue.o ../../../objs/Defines.o ../../../objs/MessageImporter.o ../../../objs/PathContainer.o ../../../objs/Shape.o ../../../objs/ShapeContainer.o ../../../objs/VectorPath.o ../../../objs/GradientTransformable.o ../../../objs/Style.o ../../../objs/StyleContainer.o ../../../objs/Transformable.o ../../../objs/AffineTransformer.o ../../../objs/ContourTransformer.o ../../../objs/PathSource.o ../../../objs/PerspectiveTransformer.o ../../../objs/StrokeTransformer.o ../../../objs/Transformer.o ../../../objs/TransformerFactory.o ../../../objs/Icon.o ../../../objs/IconRenderer.o ../../../objs/IconUtils.o
make[1]: se sale del directorio '/home/cmkat/src/V-OS-master/src/libs/icon'
make[1]: se entra en el directorio '/home/cmkat/src/V-OS-master/src/libs/linprog'
gcc -include build/BeOSBuildCompatibility.h -Wall -Wpointer-arith -Wcast-align -Wsign-compare -Wno-multichar -c -g -O2 -pipe `cat ../../../cosmoe.specs` -fPIC -Woverloaded-virtual -Wno-ctor-dtor-privacy -Wnon-virtual-dtor -fexceptions -fpermissive -M Constraint.cpp | sed 's%^\(.*\):%objs\/\1:%' > objs/*.d
ar rcs ../../../objs/liblinprog.a objs/ActiveSetSolver.o objs/Constraint.o objs/LayoutOptimizer.o objs/LinearSpec.o objs/Summand.o objs/Variable.o
make[1]: se sale del directorio '/home/cmkat/src/V-OS-master/src/libs/linprog'
make[1]: se entra en el directorio '/home/cmkat/src/V-OS-master/src/libs/agg'
ar rcs ../../../objs/libagg.a ../../../objs/agg_arc.o ../../../objs/agg_arrowhead.o ../../../objs/agg_bezier_arc.o ../../../objs/agg_bspline.o ../../../objs/agg_curves.o ../../../objs/agg_embedded_raster_fonts.o ../../../objs/agg_gsv_text.o ../../../objs/agg_image_filters.o ../../../objs/agg_line_aa_basics.o ../../../objs/agg_line_profile_aa.o ../../../objs/agg_rounded_rect.o ../../../objs/agg_sqrt_tables.o ../../../objs/agg_trans_affine.o ../../../objs/agg_trans_double_path.o ../../../objs/agg_trans_single_path.o ../../../objs/agg_trans_warp_magnifier.o ../../../objs/agg_vcgen_bspline.o ../../../objs/agg_vcgen_contour.o ../../../objs/agg_vcgen_dash.o ../../../objs/agg_vcgen_markers_term.o ../../../objs/agg_vcgen_smooth_poly1.o ../../../objs/agg_vcgen_stroke.o ../../../objs/agg_vpgen_clip_polygon.o ../../../objs/agg_vpgen_clip_polyline.o ../../../objs/agg_vpgen_segmentator.o
make[1]: se sale del directorio '/home/cmkat/src/V-OS-master/src/libs/agg'
make[1]: se entra en el directorio '/home/cmkat/src/V-OS-master/src/system'
make[1]: No se hace nada para 'all'.
make[1]: se sale del directorio '/home/cmkat/src/V-OS-master/src/system'
make[1]: se entra en el directorio '/home/cmkat/src/V-OS-master/src/kits'
gcc -include build/BeOSBuildCompatibility.h -Wall -Wpointer-arith -Wcast-align -Wsign-compare -Wno-multichar -c -g -O2 -pipe `cat ../../cosmoe.specs` -fPIC -fpermissive -Woverloaded-virtual -Wno-ctor-dtor-privacy -Wnon-virtual-dtor -fexceptions support/ByteOrder.cpp -o ../../objs/ByteOrder.o
support/ByteOrder.cpp:158:1: warning: keyword ‘export’ not implemented, and will be ignored
 export double __swap_double(double arg)
 ^
support/ByteOrder.cpp:158:15: error: expected ‘template’ before ‘__swap_double’
 export double __swap_double(double arg)
               ^
support/ByteOrder.cpp:158:39: warning: ISO C++ forbids declaration of ‘__swap_double’ with no type [-fpermissive]
 export double __swap_double(double arg)
                                       ^
support/ByteOrder.cpp: In function ‘int __swap_double(double)’:
support/ByteOrder.cpp:158:39: error: ambiguating new declaration of ‘int __swap_double(double)’
In file included from support/ByteOrder.cpp:7:0:
/home/cmkat/src/V-OS-master/headers/os/support/ByteOrder.h:122:15: note: old declaration ‘double __swap_double(double)’
 extern double __swap_double(double arg);
               ^
support/ByteOrder.cpp: At global scope:
support/ByteOrder.cpp:164:1: warning: keyword ‘export’ not implemented, and will be ignored
 export float  __swap_float(float arg)
 ^
support/ByteOrder.cpp:164:15: error: expected ‘template’ before ‘__swap_float’
 export float  __swap_float(float arg)
               ^
support/ByteOrder.cpp:164:37: warning: ISO C++ forbids declaration of ‘__swap_float’ with no type [-fpermissive]
 export float  __swap_float(float arg)
                                     ^
support/ByteOrder.cpp: In function ‘int __swap_float(float)’:
support/ByteOrder.cpp:164:37: error: ambiguating new declaration of ‘int __swap_float(float)’
In file included from support/ByteOrder.cpp:7:0:
/home/cmkat/src/V-OS-master/headers/os/support/ByteOrder.h:123:15: note: old declaration ‘float __swap_float(float)’
 extern float  __swap_float(float arg);
               ^
../../makefile.rules:25: fallo en las instrucciones para el objetivo '../../objs/ByteOrder.o'
make[1]: *** [../../objs/ByteOrder.o] Error 1
make[1]: se sale del directorio '/home/cmkat/src/V-OS-master/src/kits'
Makefile.common:7: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 1

**Comment by Barrett17** [comment] 2018-10-23 10:57
Sorry, the buildsystem is just the same as cosmoe right now and needs to be replaced with something more adequate.

**Comment by cb88** [comment] 2018-10-26 14:55
A ninja generator perhaps? https://github.com/ninja-build/ninja/wiki/List-of-generators-producing-ninja-build-files

Many build tools are hard to grask for someone from the outside... perhaps something that is pretty straight forward? Some of the python oneoffs, and some like buildfox look easy enough to understand the whole thing.

**Comment by Barrett17** [comment] 2018-10-28 15:50
I'd be oriented towars using the Jam based buildsystem of Haiku. I will do that when I import the codec_kit into the code. I'd like to have some compatibility with Haiku for both exchanging patches and ease of development. However, thank you for your suggestions, I will keep that into consideration :)

**Comment by cb88** [comment] 2018-10-29 04:28
That seems reasonable, Jam isn't terribly hard to understand either it has quirks but nothing terrible.

**Comment by Barrett17** [comment] 2019-03-19 14:34
@cb88 going to reconsider your proposal about ninja generator. I'm also considering cmake.
I think reworking the Haiku buildsystem makes little sense now, I just overlooked into that.

**Comment by Barrett17** [comment] 2019-03-19 14:35
So, if I understand correctly, CMake will allow me to generate ninja files from any project?

**Comment by cb88** [comment] 2019-03-19 15:17
Any cmake project I think though of course there may be caveats... IIRC the webkit port to Haiku actually uses ninja as it is much faster... abandoning Jam and going it on your own may of course be counter productive. Then there is of course Ham which could be worked on.

**Comment by Barrett17** [comment] 2019-03-19 15:22
What changed is that I'm not willing anymore to upstream my code to the Haiku project. So, the need to have the same buildsystem is considerably reduced, to the point that now considering jam being broken, I changed idea. Ham is interesting, but I'm just one person and I feel like I will not be able to keep up with everything. If someone is willing to help, things can be different...

**Comment by cb88** [comment] 2019-03-19 15:40
Of which everyone is exceedingly aware of. I don't think it is likely many will help your fork.. people get along with people that can get along and you haven't won the hearts of anyone with your arguments (sometimes it's better to not argue or complain) as doing so burns other's patience. Yes, yes sometimes people are jerks and difficult to deal with but you had commit access still and eventually exhausted what patience there rest had. Honestly converting to cmake seems like a lot of work, and it would have drawbacks also. Perhaps the linux kernel build system if you intend to still make a Be/Linux hybrid. 

Dunno what you do for work but that's probably an avenue to persue you have the coding skills... working at an office on a team may help round you out a bit. I'd avoid telecommuting though.

**Comment by Barrett17** [comment] 2019-03-19 15:49
> Of which everyone is exceedingly aware of. I don't think it is likely many will help your fork.. people get along with people that can get along and you haven't won the hearts of anyone with your arguments (sometimes it's better to not argue or complain) as doing so burns other's patience.

I believe results will count. I think you should try collaborating with me before saying that...

 Yes, yes sometimes people are jerks and difficult to deal with but you had commit access still and eventually exhausted what patience there rest had. 

Or they exhausted my patience? Try to consider that..

Honestly converting to cmake seems like a lot of work, and it would have drawbacks also. Perhaps the linux kernel build system if you intend to still make a Be/Linux hybrid.

It's going to be less work than you imagine, believe me :)

> 
> Dunno what you do for work but that's probably an avenue to persue you have the coding skills... working at an office on a team may help round you out a bit. I'd avoid telecommuting though.

I work at a company and I'm appreciated for both my coding and social skills. I'm always able to keep moral up and they enjoy working with me. Discussions about design decisions is not a problem there, as they trust me enough and I'm able to take other suggestions.

What happened in the Haiku project is an exception in my life. And a lot of people (even devs) told me it's really a shame about what happened. But I want to leave this apart as this is offtopic, feel free to contact me privately if you want to discuss that.

**Comment by cb88** [comment] 2019-03-19 16:37
I think you may have missed it but I suggested https://github.com/embedded-it/kbuild-template

**Comment by Barrett17** [comment] 2019-03-19 16:40
What's in your opinion the strongest argument to use kbuild?

**Comment by cb88** [comment] 2019-03-20 16:47
It's the same build system as the Linux kernel... that's all. It's also relatively straightforward compared to more complex tools like cmake or autotools. It's not so much geared toward building in different environments as building in a single environment, with lots of configuration.

**Comment by Barrett17** [comment] 2019-03-20 23:24
In the end I don't care about the best buildsystem. I think ninja showed to be very mature in chrome and android, so I think I will start with cmake+makefile and when the project gets bigger I may switch to ninja (maybe using cmake, maybe not).

**Comment by Barrett17** [comment] 2019-03-26 12:28
The issue is fixed now. We have a completely redesigned build system based on cmake. Note that build instructions are outdated.

In the end, I choose to go with cmake used as ninja generator. Proven to be extremely extensible, and I think it's more than adequate for this project. When and if the Haiku project switch to something less broken, I may reconsider the choice. It'd be nice to keep the repository as similar as possible, but there are multiple reasons that prevent this to happen from both projects.

**Closed by Barrett17** 2019-03-26 12:28 UTC
